version: "2.2"
services:
  elastica:
    build:
      context: .
      network: elastica_network
  #  image: ruflin/elastica
    ports:
      - "9200:9200"
    links:
      - nginx
      - elasticsearch
    depends_on:
      - elasticsearch
      - nginx
    environment:
      - ES_HOST=elasticsearch
      - PROXY_HOST=nginx
  elasticsearch:
    build:
      context: ./env/elasticsearch/
      network: elastica_network
  #  image: ruflin/elasticsearch-elastica
    volumes_from:
      - data
  nginx:
    build:
      context: ./env/nginx/
      network: elastica_network
  #  image: ruflin/nginx-elastica
    links:
      - elasticsearch
  # data container to share data between elasticsearch nodes for snapshot testing
  data:
    image: ruflin/elastica-data
    volumes:
      - "/tmp/backups/backup1"
      - "/tmp/backups/backup2"

